# from: https://trashmoon.com/blog/2022/automating-steam-releases-for-html-games-with-electron-forge-and-github-actions/
name: Build/release

# Run this workflow whenever a tag that starts with v is pushed to github.
on: [push]
  # COMMENT OUT FOR TESTING
  # push:
    # tags:
    #   - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      # Wine is required in order to generate an Electron build for Windows from
      # an Ubuntu machine.
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine-stable

      # Install dependencies for the app
      - name: Run app install
        # use yarn instead of npm for consistency with our lock file
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      # Move all the game files into a build/ directory.
      - name: Run build
        run: npm run build

      # Install dependencies for electron
      - name: Run electron install
        # use yarn instead of npm for consistency with our lock file
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: electron # will run `yarn install` command in `electron` subfolder

      # npm run make uses Electron Forge, see package.json above for details.
      # We have to run make three times, once for each platform. This step
      # generates three directories, corresponding to each platform.
      # Ubuntu is set as our environment, so platform auto resolves to that.
      # Notice the working-directory is now ./electron!
      - name: Copy HTML app to electron/, and make Electron packages
      # npm run make -- --arch="ia32,x64" --platform=win32
        run: |
          node ../scripts/prepare-electron.js
          npm run make
          npm run make -- --platform=win32
          npm run make -- --arch="arm64,x64" --platform=darwin
        working-directory: ./electron

      - name: Upload darwin x64 (intel chip)
        uses: actions/upload-artifact@v4
        with:
          name: gemhunter_electron_darwin_x64
          path: electron/out/make/zip/darwin/x64

      - name: Upload darwin arm64 (M1 silicon)
        uses: actions/upload-artifact@v4
        with:
          name: gemhunter_electron_darwin_arm64
          path: electron/out/make/zip/darwin/arm64

      - name: Upload linux
        uses: actions/upload-artifact@v4
        with:
          name: gemhunter_electron_linux
          path: electron/out/make/zip/linux/x64

      - name: Upload win32 x64 (64 bit)
        uses: actions/upload-artifact@v4
        with:
          name: gemhunter_electron_win32_x64
          path: electron/out/make/zip/win32/x64

        - name: Upload win32 ia32 (32 bit)
        uses: actions/upload-artifact@v4
        with:
          name: gemhunter_electron_win32_ia32
          path: electron/out/make/zip/win32/x64

      # npm run make uses Electron Forge, see package.json above for details.
      # We have to run make three times, once for each platform. This step
      # generates three directories, corresponding to each platform.
      # Ubuntu is set as our environment, so platform auto resolves to that.
      # Notice the working-directory is now ./electron!
      # - name: Copy HTML app to electron
      #   run: node ../scripts/prepare-electron.js
      #   working-directory: ./electron

      # - name: Make linux Electron package
      #   run: npm run make
      #   working-directory: ./electron

      # - name: Upload linux Electron package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gemhunter_electron_linux
      #     path: electron/out

      # - name: Make darwin Electron package
      #   run: npm run make -- --platform=darwin
      #   working-directory: ./electron

      # - name: Upload darwin Electron package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gemhunter_electron_darwin
      #     path: electron/out

      # - name: Make win32 Electron package
      #   run: npm run make -- --platform=win32
      #   working-directory: ./electron

      # - name: Upload win32 Electron package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gemhunter_electron_win32
      #     path: electron/out

      # - name: Download all workflow run artifacts
      #   uses: actions/download-artifact@v4

      # View this action's source code and documentation at
      # https://github.com/game-ci/steam-deploy. Note that this action only
      # works in ubuntu environments. If you want to run in Mac OS or Windows
      # environments, you'll need to write your own deploy script.
      # The depot{number}Path parameters correspond to the directories created
      # in the previous step by npm run make.
      # COMMENT OUT UNTIL SECRETS ARE SETUP
      # - name: Deploy to Steam
      #   uses: game-ci/steam-deploy@v1.1.0
      #   with:
      #     username: ${{ secrets.STEAM_USERNAME }}
      #     password: ${{ secrets.STEAM_PASSWORD }}
      #     configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
      #     ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
      #     ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
      #     appId: your app id goes here
      #     buildDescription: ${{ github.ref }}
      #     rootPath: electron/out
      #     depot1Path: ${{ github.repository }}-darwin-x64
      #     depot2Path: ${{ github.repository }}-win32-x64
      #     depot3Path: ${{ github.repository }}-linux-x64
      #     releaseBranch: prerelease
